# Generated by Django 2.1 on 2018-08-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostModal',
        ),
    ]
